# Page settings

baseurl = ""
languageCode = "en-us"
title = "Yu (Lenny) Liang"
# theme = "hugo-orbit-theme"

# Do not build files for websites. Need them? Set to false
disableKinds=["404", "RSS", "sitemap"]

[blackfriday]
fractions = false
hrefTargetBlank = true

[params]

# Meta
    description = "Yu (Lenny) Liang, PhD"
    author = "Yu (Lenny) Liang"

# Theme styles
    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Yu Liang"
        tagline = "Senior researcher and lecturer"
        avatar = "photo.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto:yulianglenny@gmail.com"
        title = "yulianglenny@gmail.com"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "PhD in Computer Science"
        college = "City University of Hong Kong"
        dates = "2016 - 2021"

        [[params.education.list]]
        degree = "MSc in Computer Science"
        college = "Shandong University"
        dates = "2010 - 2013"

        [[params.education.list]]
        degree = "BSc in Computer Science"
        college = "Shandong University"
        dates = "2006 - 2010"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Chinese"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Research Interests"

        [[params.interests.list]]
        interest = "File systems and memory management of mobile systems"

        [[params.interests.list]]
        interest = "Hardware and software co-design for mobile devices"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "I am currently a Senior Researcher and Lecturer at ETH Zurich (in [SAFARI group](https://safari.ethz.ch/group-members/) led by [Prof. Onur Mutlu](https://people.inf.ethz.ch/omutlu/)). I received my Ph.D. from the City University of Hong Kong (co-supervised by [Prof. Tei-Wei Kuo](https://www.csie.ntu.edu.tw/~ktw/) and [Prof. Chun Jason Xue](https://scholar.google.com/citations?user=C6oyGQkAAAAJ&hl=en)). I focus on the design and optimization of mobile operating systems and architectures, aiming to meet the needs of rapid application launching and response, reduce energy consumption, address privacy and security issues, and prolong the service life of devices."

     # News section
    [params.news]
        enable = true
        icon = "fa-bullhorn"
        title = "News"
        
        [[params.news.list]]
        date = "Nov 3, 2024"
        details = "Our paper is accepted by HPCA 2025 ! "

        [[params.news.list]]
        date = "Feb 29, 2024"
        details = "Our paper is accepted by ASPLOS 2024 ! "

        [[params.news.list]]
        date = "Nov 1, 2023"
        details = "Our paper is accepted by TPDS !"
        
    # Objective section
    [params.objective]
        enable = true
        icon = "fa-bullhorn"
        title = "Objective and Mindset"
        
        [[params.objective.list]]
        item = "**Objective**: Dedicate my research to making meaningful contributions to the research community and society."
        
        [[params.objective.list]]
        item = "**Mindset**: Think big and aim high."

    # Publications section
    [params.publications]
        enable = true
        icon = "fa-book"
        title = "Publications"
        intro = ""
        subtitlea ="Conference Papers"
        subtitleb ="Journal Papers"

    # Conference papers
    [[params.conferencepapers.list]]
        enable = true
        cite = "HPCA25"
        title = "[Ariadne: Hotness-Aware and Size-Adaptive Compressed Swap Scheme for Mobile Devices]"
        author = "**Yu Liang**; Aofeng Shen; Chun Jason Xue; Riwei Pan; Haiyu Mao; Nika Mansouri Ghiasi; Qingcai Jiang; Rakesh Nadig; Lei Li; Rachata Ausavarungnirun; Mohammad Sadrosadati; Onur Mutlu;"
        journal = "In the 31st IEEE International Symposium on High-Performance Computer Architecture (**HPCA'25**), Las Vegas, USA, 2025-3-1 to 2025-3-5"
        note = " "
     
     [[params.conferencepapers.list]]
        enable = true
        cite = "ASPLOS 24"
        title = "[More Apps, Faster Hot-Launch on Mobile Devices via Fore/Background-aware GC-Swap Co-design](https://dl.acm.org/doi/10.1145/3620666.3651377)"
        author = "Jiacheng Huang; Yunmo Zhang; Junqiao Qiu; **Yu Liang**; Rachata Ausavarungnirun; Qingan Li; Chun Jason Xue;"
        journal = "In the ACM International Conference on Architectural Support for Programming Languages and Operating Systems (**ASPLOS'24**), San Diego, USA, 2024-4-27 to 2024-5-1"
        note = " "
        
    [[params.conferencepapers.list]]
        enable = true
        cite = "eurosys23"
        title = "[ICE: Collaborating Memory and Process Management for User Experience on Resource-limited Mobile Devices](https://dl.acm.org/doi/abs/10.1145/3552326.3567497)"
        author = "Changlong Li; **Yu Liang***; Rachata Ausavarungnirun; Zongwei Zhu; Liang Shi; Chun Jason Xue;"
        journal = "In the 18th European Conference on Computer Systems (**EuroSys'23**), Rome, Italy, 2023-5-9 to 2023-5-12"
        note = " (**coresponding author**)"

    [[params.conferencepapers.list]]
        enable = true
        cite = "fast22"
        title = "[CacheSifter: Sifting Cache Files for Boosted Mobile Performance and Lifetime](https://www.usenix.org/conference/fast22/presentation/liang)"
        author = "**Yu Liang**; Riwei Pan; Tianyu Ren; Yufei Cui; Rachata Ausavarungnirun; Xianzhang Chen; Changlong Li; Tei-Wei Kuo; Chun Jason Xue;"
        journal = "In the 20th USENIX Conference on File and Storage Technologies (**FAST'22**), July 10-14, 2022, Santa Clara, CA, USA, 2022-2-22 to 2022-2-24"
        note = ""

    [[params.conferencepapers.list]]
        enable = true
        cite = "atc20"
        title = "[Acclaim: Adaptive Memory Reclaim to Improve User Experience in Android Systems](https://www.usenix.org/conference/atc20/presentation/liang-yu)"
        author = "**Yu Liang**; Jinheng Li; Rachata Ausavarungnirun; Riwei Pan; Liang Shi; Tei-Wei Kuo; Chun Jason Xue;"
        journal = "In 2020 USENIX Annual Technical Conference (**ATC'20**), Boston, MA, USA, 2020-7-15 to 2020-7-17 "
        note = ""

    [[params.conferencepapers.list]]
        enable = true
        cite = "hotstorage20"
        title = "[Differentiating Cache Files for Fine-grain Management to Improve Mobile Performance and Lifetime](https://www.usenix.org/conference/hotstorage20/presentation/liang)"
        author = "**Yu Liang**; Jinheng Li; Xianzhang Chen; Rachata Ausavarungnirun; Riwei Pan; Tei-Wei Kuo; Chun Jason Xue;"
        journal = "In the 12th USENIX Workshop on Hot Topics in Storage and File Systems (**HotStorage'20**), Boston, MA, USA, 2020-7-13 to 2020-7-14"
        note = ""

    [[params.conferencepapers.list]]
        enable = true
        cite = "hotstorage19"
        title = "[Mismatched Memory Management of Android Smartphones](https://www.usenix.org/conference/hotstorage19/presentation/liang)"
        author = "**Yu Liang**; Qiao Li; Chun Jason Xue;"
        journal = "In the 11th USENIX Workshop on Hot Topics in Storage and File Systems (**HotStorage'19**), RENTON, WA, USA, 2019-7-8 to 2019-7-9"
        note = ""

    [[params.conferencepapers.list]]
        enable = true
        cite = "sac19"
        title = "[Optimizing Fragmentation and Segment Cleaning for CPS based Storage Devices](https://dl.acm.org/doi/abs/10.1145/3297280.3297306)"
        author = "Qi Li; Aosong Deng; Congming Gao; **Yu Liang**; Liang Shi; Edwin H.-M. Sha;"
        journal = "In 2019 ACM/SIGAPP Symposium on Applied Computing (**SAC'19**), Limassol, Cyprus, 2019-4-8 to 2019-4-12"
        note = ""

    [[params.conferencepapers.list]]
        enable = true
        cite = "rtcsa17"
        title = "[An Empirical Study of F2FS on Mobile Devices](https://ieeexplore.ieee.org/abstract/document/8046304)"
        author = "**Yu Liang**; Chenchen Fu; Yajuan Du; Aosong Deng; Mengying Zhao; Liang Shi; Chun Jason Xue;"
        journal = "In _IEEE International Conference on Embedded and Real-Time Computing Systems and Applications (**RTCSA'17**), Hsinchu, Taiwan, China, 2017-8-16 to 2017-8-18"
        note = ""

    # Journal papers
    [[params.journalpapers.list]]
        enable = true
        cite = "tpds23"
        title = "[Flexible and Efficient Memory Swapping Across Mobile Devices with LegoSwap](https://ieeexplore.ieee.org/document/10314796)"
        author = "Changlong Li, **Yu Liang***; Liang Shi; Chao wang; Chun Jason Xue; Xuehai Zhou"
        journal = "_IEEE Transactions on Parallel and Distributed Systems (**TPDS**)_, 2023"
        note = "(**coresponding author**)"

    [[params.journalpapers.list]]
        enable = true
        cite = "tc21"
        title = "[Read-Ahead Efficiency on Mobile Devices: Observation, Characterization, and Optimization](https://ieeexplore.ieee.org/abstract/document/9054972)"
        author = "**Yu Liang**; Riwei Pan; Yajuan Du; Chenchen Fu; Liang Shi; Tei-Wei Kuo; Chun Jason Xue;"
        journal = "_IEEE Transactions on Computers (**TC**)_, 2021, 70: 99-110"
        note = ""

    [[params.journalpapers.list]]
        enable = true
        cite = "tcad21"
        title = "[iTRIM: I/O-Aware TRIM for Improving User Experience on Mobile Devices](https://ieeexplore.ieee.org/abstract/document/9209165)"
        author = "**Yu Liang**; Cheng Ji; Chenchen Fu; Rachata Ausavarungnirun; Qiao Li; Riwei Pan; Siyu Chen;Liang Shi; Tei-Wei Kuo; Chun Jason Xue;"
        journal = "_IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems (**TCAD**)_, 2021, 40: 1782-1795"
        note = ""

    [[params.journalpapers.list]]
        enable = true
        cite = "tcad20"
        title = "[SEAL: User Experience-Aware Two-Level Swap for Mobile Devices](https://ieeexplore.ieee.org/abstract/document/9211475)"
        author = "Changlong Li; Liang Shi; **Yu Liang**; Chun Jason Xue;"
        journal = "_IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems (**TCAD**)_, 2020, 39: 4102-4114"
        note = ""

    [[params.journalpapers.list]]
        enable = true
        cite = "tr20"
        title = "[Process Variation Aware Read Performance Improvement for LDPC-Based nand Flash Memory](https://ieeexplore.ieee.org/abstract/document/8642917)"
        author = "Qiao Li; Liang Shi; Yejia Di; Congming Gao; Cheng Ji; **Yu Liang**; Chun Jason Xue;"
        journal = "_IEEE Transactionson Reliability (**TR**)_, 2020, 69: 310-321"
        note = ""

    [[params.journalpapers.list]]
        enable = true
        cite = "tos20"
        title = "[Inspection and Characterization of App File Usage in Mobile Devices](https://dl.acm.org/doi/abs/10.1145/3404119)"
        author = "Cheng Ji; Riwei Pan; Li-Pin Chang; Liang Shi; Zongwei Zhu; **Yu Liang**; Tei-Wei Kuo; Chun Jason Xue;"
        journal = "_ACM Transactions on Storage (**TOS**)_, 2020, 16: 1-25"
        note = ""

    [[params.journalpapers.list]]
        enable = true
        cite = "sigbed19"
        title = "[Boosting read-ahead efficiency for improved user experience on mobile devices](https://dl.acm.org/doi/abs/10.1145/3373400.3373412)"
        author = "**Yu Liang**; Yajuan Du; Chenchen Fu; Riwei Pan; Liang Shi; Chun Jason Xue;"
        journal = "_SIGBED Review_, 2019, 16: 75-80"
        note = ""

    # Patents Section
    [params.patents]
        enable = true
        icon = "fa-file"
        title = "Patents"
        
        [[params.patents.list]]
        patent = "Chun Jason Xue, Riwei Pan, **Yu Liang**, Pengcheng Fu, Jingjing Mao. [Data storage method and device](https://patents.google.com/patent/CN118625993A/en?oq=CN118625993A), Patent no.: CN118625993A, 2024, China."
 
        [[params.patents.list]]
        patent = "Chun Jason Xue, **Yu Liang**, Lei Li, Jian Yi, Jingjing Mao. [Memory allocation method, electronic equipment and storage medium](https://patents.google.com/patent/CN118535315A/en?oq=CN118535315A), Patent no.: CN118535315A, 2024, China."
 
        [[params.patents.list]]
        patent = "Chun Jason Xue, Riwei Pan, **Yu Liang**, Jing Qian, Jiaxin Li. [File searching method and device based on electronic equipment](https://patents.google.com/patent/CN116821076A/en?oq=CN116821076A), Patent no.: CN116821076A, 2023, China."
 
        [[params.patents.list]]
        patent = "Chun Jason Xue, Riwei Pan, **Yu Liang**, Jiaxin Li, Jing Qian. [Data deduplication method and electronic equipment](https://patents.google.com/patent/CN116821075A/en?oq=CN116821075A), Patent no.: CN116821075A, 2023, China."

        [[params.patents.list]]
        patent = "Jiacheng Huang, Qingan Li, **Yu Liang**, Chun Jason Xue, Jiaxin Li, Jing Qian. [Method for controlling memory and electronic equipment](https://patents.google.com/patent/CN116820734A/en?oq=CN116820734A), Patent no.: CN116820734A, 2023, China."

        [[params.patents.list]]
        patent = "Chun Jason Xue, **Yu Liang**, Riwei Pan, Zhipeng Li, Ge Qiu, Jing Qian, Jian Yi, Jiaxin Li. [Management method and management device for cache files](https://patents.google.com/patent/CN115617255A/en?oq=CN115617255A), Patent no.: CN115617255A, 2023, China."

        [[params.patents.list]]
        patent = "Chun Jason Xue, Riwei Pan, **Yu Liang**, Zhipeng Li, Ge Qiu, Jing Qian, Jian Yi, Jiaxin Li, [Memory space management method and memory space management device](https://patents.google.com/patent/CN115543600A/en?oq=CN115543600A), Patent no.: CN115543600A, 2022, China."

        [[params.patents.list]]
        patent = "Jason Chun Xue, **Yu Liang**, Liang Shi. [Method for accelerating starting of application program and electronic equipment](https://patents.google.com/patent/CN112783564B/en?oq=CN112783564B), Patent no.: CN112783564B, 2021, China."

        [[params.patents.list]]
        patent = "Jason Chun Xue, Liang Shi, **Yu Liang**. [Hot and cold data separation method and device](https://patents.google.com/patent/CN105677242B/en?oq=CN105677242B), Patent no.: CN105677242B, 2018, China."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-area-chart"
        title = "Highlighted Research Impact"

       
        [[params.jobs.list]]
        position = "F2FS File System Deployment and Optimization"
        dates = ""
        company = ""
        details = "1. I contributed to the adoption of F2FS on commercial mobile devices, conducting evaluations of its advantages and disadvantages [C9] and implementing numerous optimizations [J3, C8, P9] for our collaborating vendor. This collaborator became the first smartphone vendor to adopt F2FS. Today, F2FS has become the de facto standard file system for mobile devices, powering billions of devices worldwide.\n\n2. A F2FS TRIM optimization "f2fs: relax async discard commands more" motivated by my paper [J3] has been submitted to the Linux kernel Archives by our collaborator.)"

        [[params.jobs.list]]
        position = "Mobile Kernel Optimization"
        dates = ""
        company = ""
        details = "1. Cache file optimization [C4, P6] and data storage/deduplication techniques [P1, P3, P4] have been adopted by our collaborating vendor and implemented in their OS to optimize storage space on mobile devices. Notably, [P4] was highlighted as a core competency during their product launch. \n\n2.Developed several memory management optimization prototypes for mobile devices, based on research papers [J2, C2, C5] and patents [P2, P5, P6]. Some of these prototypes have been adopted by commercial smartphones, benefiting over 400 million users."
        
        [[params.jobs.list]]
        position = "Joint Optimization of OS and eMMC Controller"
        dates = ""
        company = ""
        details = "1. Aiming at the data security of F2FS file system, a metadata and normal data separated storage scheme is proposed.\n\n2. To improve eMMC lifetime, we propose reducing unnecessary data writebacks based on the access patterns of mobile application files.\n\n\tThe proposed techniques are planned to be implemented on the **eMMC commercial products** of our cooperative eMMC controller vendor."

    # Services section
    [params.services]
        enable = true
        icon = "fa-users"
        title = "Academic Services"

        [[params.services.list]]
        item = "**Program Committee**: ATC'23, ATC'24, DSN'24, SYSTOR'24, EuroSys'25, ATC'25, FAST'25, and FAST'26."

       # [[params.services.list]]
       # item = "Session chair of ATC'23"

       # [[params.services.list]]
       # item = "The artifact evaluation committee of ATC/OSDI'22, ATC/OSDI'23, ASPLOS'23, and SOSP'23"

        [[params.services.list]]
        item = "**Reviewer**: IEEE Transactions on Computers, ACM Transactions on Storage, International Journal of Intelligent Systems, and ACM Computing Surveys."

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Yu Liang"
